name: DataDash QA Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Scraper Script - 24f2002912@ds.study.iitm.ac.in
        run: node scraper.js
